<?php get_header(); ?>
    <div class="container contact clearfix">
        <div class="col-xs-12 margin-bottom">
            <?php if (qtrans_getLanguage() == 'es'){ ?>
                <h2 class="red">Política de Privacidad</h2>
                <p>Aviso de Privacidad Select Team Becas</p>
                <p></p>
            <?php } else { ?>
                <h2 class="red">Privacy Policy</h2>
                <p>Privacy Policy Select Team Becas</p>
                <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. In fermentum ut lectus in aliquet. Praesent vulputate cursus erat, vel ultricies lectus aliquam eu. Duis suscipit a tortor vel porta. Nullam sed egestas eros, vel tincidunt erat. In sed vestibulum purus, sit amet ullamcorper purus. Donec eu fringilla augue. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Integer lorem justo, tincidunt et lacus dictum, dignissim euismod diam. Vestibulum vel neque odio.</p>
                <p>Pellentesque auctor nibh eget congue placerat. Integer et sollicitudin ante. Fusce hendrerit porta mauris, at vestibulum lacus viverra eget. Suspendisse imperdiet purus in metus luctus varius at ac orci. Sed cursus diam turpis, at interdum lacus tristique id. Morbi ac luctus arcu. Aliquam nec tellus dui. Nulla facilisi. Sed fermentum orci turpis, in mollis ligula placerat eget. Curabitur in velit dignissim, congue neque nec, lacinia massa. Vestibulum a sem a nulla vulputate pretium quis eget quam. Vivamus ante tortor, efficitur nec accumsan hendrerit, finibus eget nunc. Integer sed urna purus. Phasellus efficitur interdum tortor, non tincidunt elit varius vitae.</p>
                <p>Fusce vitae sem varius ligula consectetur maximus. Donec semper dictum odio sagittis luctus. Etiam ultrices, libero at vestibulum vulputate, metus lacus dapibus felis, eu aliquam justo odio quis leo. Fusce bibendum varius neque, sit amet interdum augue molestie vitae. Aenean eget felis nunc. Sed feugiat sit amet massa sit amet sagittis. Mauris fermentum efficitur lacus. Mauris et libero ac ex ornare vehicula ut non nisi. Vestibulum porttitor, purus id posuere maximus, odio risus iaculis purus, condimentum suscipit ante orci id arcu.</p>
                <p>Integer rhoncus vulputate dui. Curabitur consectetur sem non sem suscipit commodo. Ut ut nunc malesuada, aliquet urna pellentesque, mollis leo. Interdum et malesuada fames ac ante ipsum primis in faucibus. Praesent scelerisque eros nec felis efficitur vestibulum id in turpis. Nulla facilisi. Duis interdum ipsum ut magna vulputate, elementum luctus purus tincidunt. In sed ultrices orci, at interdum dui. Proin malesuada ante lectus, ut dapibus sapien euismod blandit. Suspendisse dictum, mi ullamcorper dapibus congue, dolor elit interdum odio, at placerat nisi nunc et est. Nam massa justo, elementum non turpis in, tempor venenatis augue. In ante felis, fringilla sit amet lobortis nec, hendrerit hendrerit ipsum. Sed gravida mauris sed diam consequat auctor.</p>
                <p>Vivamus ultrices tincidunt placerat. Vestibulum nulla felis, tristique eu posuere ac, vehicula sed mauris. In lacus felis, accumsan sed diam et, pellentesque lobortis elit. Etiam vitae vestibulum risus, sed cursus ante. Sed vulputate volutpat augue, non vehicula nisi porttitor et. Pellentesque id tempus lacus. Suspendisse aliquet, dolor vel condimentum vulputate, nulla turpis sagittis eros, a gravida arcu magna semper velit. Pellentesque maximus cursus consequat. Suspendisse eu efficitur dui, quis egestas tellus. Vivamus nibh libero, bibendum sed dictum in, consequat in nisl. Sed vehicula, mi id aliquet congue, ex ipsum egestas tellus, a vehicula sem augue eu arcu. Aliquam in tincidunt felis.</p>
            <?php } ?>
        </div>
    </div>
<?php get_footer(); ?>